export { WX_API_TYPE } from './WxApiType'
export { WX_DOMAIN } from './WxDomain'
export { WX_TRADE_TYPE } from './TradeType'
export { WxPay } from './WxPay'
export { WxPayApiConfig } from './WxPayApiConfig'
export { WxPayApiConifgKit } from './WxPayApiConifgKit'
